const items = [
    {
        itemId: 0,
        itemName: "Waffle",
        ItemPrice: 6.50,
        quantity: 50,
        description: "Waffle with Berries",
        imageUrl: "assets/images/image-waffle-desktop.jpg",
    },
    {
        itemId: 1,
        itemName: "Crème Brûlée",
        ItemPrice: 7.00,
        quantity: 50,
        description: "Vanilla Bean Crème Brûlées",
        imageUrl: "assets/images/image-creme-brulee-desktop.jpg",
    },
       {
        itemId: 2,
        itemName: "Macaron",
        ItemPrice: 8.00,
        quantity: 50,
        description: "Macaron Mix of Fives",
        imageUrl: "assets/images/image-macaron-desktop.jpg",
    },
       {
        itemId: 3,
        itemName: "Tiramisu",
        ItemPrice: 5.50,
        quantity: 50,
        description: "Classic Tiramisu",
        imageUrl: "assets/images/image-creme-brulee-desktop.jpg",
    },
       {
        itemId: 4,
        itemName: "Baklava",
        ItemPrice: 4.00,
        quantity: 50,
        description: "Pistachio Baklava",
        imageUrl: "assets/images/image-baklava-desktop.jpg",
    },
       {
        itemId: 5,
        itemName: "Pie",
        ItemPrice: 5.00,
        quantity: 50,
        description: "Lemon Meringue Pie",
        imageUrl: "assets/images/image-meringue-desktop.jpg",
    },
       {
        itemId: 6,
        itemName: "Cake",
        ItemPrice: 4.50,
        quantity: 50,
        description: "Red Velvet Cake",
        imageUrl: "assets/images/image-cake-desktop.jpg",
    },
       {
        itemId: 7,
        itemName: "Brownie",
        ItemPrice: 4.50,
        quantity: 50,
        description: "Salted Caramel Brownie",
        imageUrl: "assets/images/image-brownie-desktop.jpg",
    },
       {
        itemId: 8,
        itemName: "Panna Cotta",
        ItemPrice: 6.50,
        quantity: 50,
        description: "Vanilla Panna Cotta",
        imageUrl: "assets/images/image-panna-cotta-desktop.jpg",
    },

]